server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    # Backoffice vive bajo /admin vía traefik (PATH-BASED).
    # alias hace que /admin/** apunte a la raíz real del app.
    # (Con la variante host-based esto no haría falta.)
    location /admin/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}